[toolchain]
anchor_version = "0.30.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
vanity_miner = "5YSYX6GX3wD2xTp6poLuP92FT8uiWeRFLwASsULXXYM4"

[programs.mainnet]
vanity_miner = "5YSYX6GX3wD2xTp6poLuP92FT8uiWeRFLwASsULXXYM4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://rpc.trashscan.io"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["programs/vanity-miner"]
