[features]
seeds = false
skip-lint = false

[programs.localnet]
gorbagana_bridge = "FreEcfZtek5atZJCJ1ER8kGLXB1C17WKWXqsVcsn1kPq"

[programs.mainnet]
gorbagana_bridge = "FreEcfZtek5atZJCJ1ER8kGLXB1C17WKWXqsVcsn1kPq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://rpc.trashscan.io"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["programs/bridge"]
